version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme_db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: changeme_db_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

  wordpress:
    build: .
    container_name: wordpress_site
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: changeme_db_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ../wordpress_instance:/var/www/html
      - ./:/var/www/html/wp-content/plugins/training-registration
    depends_on:
      - db
    networks:
      - wordpress_net

volumes:
  db_data:

networks:
  wordpress_net:
